{{- $pgUser := .Values.secrets.pgUser | b64enc | quote }}
{{- $pgPassword := (randAlpha 16) | b64enc | quote }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "postgresql.fullname" .) ) }}
{{- if $secret }}
{{- $pgUser = index $secret.data "pgUser" }}
{{- $pgPassword = index $secret.data "pgPassword" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  pgUser: {{ $pgUser }}
  pgPassword: {{ $pgPassword }}
