{{- $moodleUser := .Values.secrets.moodleUser | b64enc | quote }}
{{- $moodlePassword := (randAlpha 16) | b64enc | quote }}
{{- $smtpUser := .Values.mail.smtp.user | b64enc | quote }}
{{- $smtpPassword := .Values.mail.smtp.password | b64enc | quote }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "moodle.fullname" .) ) }}
{{- if $secret }}
{{- $moodleUser = index $secret.data "moodleUser" }}
{{- $moodlePassword = index $secret.data "moodlePassword" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moodle.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "moodle.labels" . | nindent 4 }}
type: Opaque
data:
  moodleUser: {{ $moodleUser }}
  moodlePassword: {{ $moodlePassword }}
  smtpUser: {{ $smtpUser }} 
  smtpPassword: {{ $smtpPassword }}
