apiVersion: v2
name: paperless-ng
description: Paperless NG Helm Chart.

maintainers:
  - name: Frédéric Aguiard
    email: frederic.aguiard@gmail.com
    url: https://github.com/nikkoura/

type: application

version: 2.0.0
appVersion: 1.1.2

dependencies:
  - name: redis
    version: 0.2.9
    repository: "https://groundhog2k.github.io/helm-charts"
  - name: postgres
    version: 0.2.8
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: postgres.enabled

sources:
  - "https://github.com/jonaswinkler/paperless-ng/"
icon: "https://github.com/jonaswinkler/paperless-ng/raw/master/resources/logo/web/png/Color%20logo%20-%20no%20background.png"
