apiVersion: v2
name: moodle
description: Moodle is a learning platform designed to provide educators, administrators and learners with a single robust, secure and integrated system to create personalised learning environments.

type: application

version: 1.1.1

appVersion: 3.9.1

dependencies: 
  - name: postgresql
    version: 1
    repository: https://nikkoura.github.io/helm-charts/
